##Recuperar todos los clientes
GET http://localhost:3000/api/cursos HTTP/1.1

###Crear un curso por id fija
POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "titulo": "Aprende programacion",
    "lenguaje":"JavaScript",
    "vistas": 0,
    "nivel": "Intermedio"
}
###Modificar un curso por id
PUT http://localhost:3000/api/cursos/programacion/10 HTTP/1.1
Content-Type: application/json

{
    "id": 10,
    "titulo": "Aprende programacion",
    "lenguaje":"JavaScript",
    "vistas": 33,
    "nivel": "Intermedio"
}

###Modificar parcialmente un curso por id
PATCH http://localhost:3000/api/cursos/programacion/4 HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "titulo": "Python intermedio",
    "lenguaje":"Python"    
}

###Eliminar un curso por id
DELETE http://localhost:3000/api/cursos/programacion/4 HTTP/1.1

###
GET http://localhost:3001/api/iva HTTP/1.1

###
GET http://localhost:3001/api/iva/1 HTTP/1.1

###
POST http://localhost:3001/api/iva HTTP/1.1
Content-Type: application/json

{
    "tipo": 22,
    "nombre": "IVA 22%"
}

###
PUT http://localhost:3001/api/iva/6 HTTP/1.1
Content-Type: application/json

{
    "tipo": 19,
    "nombre": "IVA 19%"
}

###
DELETE http://localhost:3001/api/iva/6 HTTP/1.1


###
GET http://localhost:3001/api/familias HTTP/1.1

###
GET http://localhost:3001/api/familias/4 HTTP/1.1

###
GET http://localhost:3001/api/familiasName/Familia%201 HTTP/1.1

###
POST http://localhost:3001/api/familias HTTP/1.1
Content-Type: application/json

{
    "nombre": "Familia 1"
}

###
PUT http://localhost:3001/api/familias/1 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Tablas"
}

###
DELETE http://localhost:3001/api/familias/2 HTTP/1.1


###
GET http://localhost:3001/api/clientes HTTP/1.1

###
GET http://localhost:3001/api/clientes/1 HTTP/1.1

###
GET http://localhost:3001/api//clientesName/Pepe%20Rodriguez HTTP/1.1

###
GET http://localhost:3001/api/clientesNif/76406782T HTTP/1.1

###
POST http://localhost:3001/api/clientes HTTP/1.1
Content-Type: application/json

{
    "nombreApellidos": "Pepe Rodriguez",
    "nif": "76406782T",
    "direccion": "Calle Mayor 12",
    "localidad": "Madrid",
    "cp": 28080,
    "provincia": "Madrid",
    "pais": "España",
    "telefono1": "666555444",
    "telefono2": "445566",
    "fax": "666555444",
    "email": "peperodriguez@gmail.com",
    "web": "www.peperodriguez.com",
    "contacto": "Pepe",
    "fechaAlta": "2021-01-01"
}

###
PUT http://localhost:3001/api/clientes/1 HTTP/1.1
Content-Type: application/json

{
    "nombreApellidos": "Pepe Rodriguez",
    "nif": "76406782T",
    "direccion": "Calle Mayor 12",
    "localidad": "Madrid",
    "cp": 28080,
    "provincia": "Madrid",
    "pais": "España",
    "telefono1": "666555444",
    "telefono2": "445566",
    "fax": "666555444",
    "email": "pepitoperez@hotmail.com",
    "web": "www.peperodriguez.com",
    "contacto": "Pepe",
    "fechaAlta": "2021-01-01"
}

###
DELETE http://localhost:3001/api/clientes/2 HTTP/1.1

###
GET http://localhost:3001/api/productos HTTP/1.1

###
GET http://localhost:3001/api/productos/1 HTTP/1.1

###
GET http://localhost:3001/api/productosName/Peras HTTP/1.1

###
POST http://localhost:3001/api/productos HTTP/1.1
Content-Type: application/json

{
    "nombre": "Peras",    
    "precio1": 2.5,
    "precio2": 3.5,
    "precio3": 4.5,
    "precio4": 5.5,
    "precio5": 6.5,
    "iva_id": 1,
    "familia_id": 1    
}

###
PUT http://localhost:3001/api/productos/1 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Peras de agua",
    "precio1": 2.5,
    "precio2": 3.5,
    "precio3": 4.5,
    "precio4": 5.5,
    "precio5": 6.5,
    "iva_id": 1,
    "familia_id": 1
}

###
DELETE http://localhost:3001/api/productos/1 HTTP/1.1